pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // Clone the repo and specify branch
                git branch: 'main',
                    url: 'https://github.com/your-username/alx-backend-python.git'
            }
        }

        stage('Setup Python Environment') {
            steps {
                sh '''
                python3 -m venv venv
                . venv/bin/activate
                pip3 install --upgrade pip
                pip3 install -r messaging_app/requirements.txt
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                . venv/bin/activate
                pytest --junitxml=report.xml
                '''
            }
            post {
                always {
                    junit 'report.xml'  // publish test results in Jenkins
                }
            }
        }
    }

    triggers {
        // Only manual trigger for now
    }
}
